// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/warp/v1/events.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventSetupPermissionlessInfrastructure is emitted when permissionless infrastructure is set up
type EventSetupPermissionlessInfrastructure struct {
	// creator who initiated the setup
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// mode: "create" or "transfer"
	Mode string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// mailbox_id of the module-owned mailbox
	MailboxId string `protobuf:"bytes,3,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	// routing_ism_id of the module-owned routing ISM
	RoutingIsmId string `protobuf:"bytes,4,opt,name=routing_ism_id,json=routingIsmId,proto3" json:"routing_ism_id,omitempty"`
	// token_id of the module-owned token
	TokenId string `protobuf:"bytes,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// local_domain (only for create mode)
	LocalDomain uint32 `protobuf:"varint,6,opt,name=local_domain,json=localDomain,proto3" json:"local_domain,omitempty"`
	// origin_denom (only for create mode)
	OriginDenom string `protobuf:"bytes,7,opt,name=origin_denom,json=originDenom,proto3" json:"origin_denom,omitempty"`
	// current_owner (only for transfer mode)
	CurrentOwner string `protobuf:"bytes,8,opt,name=current_owner,json=currentOwner,proto3" json:"current_owner,omitempty"`
}

func (m *EventSetupPermissionlessInfrastructure) Reset() {
	*m = EventSetupPermissionlessInfrastructure{}
}
func (m *EventSetupPermissionlessInfrastructure) String() string { return proto.CompactTextString(m) }
func (*EventSetupPermissionlessInfrastructure) ProtoMessage()    {}
func (*EventSetupPermissionlessInfrastructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_0679537d908e0877, []int{0}
}
func (m *EventSetupPermissionlessInfrastructure) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSetupPermissionlessInfrastructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSetupPermissionlessInfrastructure.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventSetupPermissionlessInfrastructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSetupPermissionlessInfrastructure.Merge(m, src)
}
func (m *EventSetupPermissionlessInfrastructure) XXX_Size() int {
	return m.Size()
}
func (m *EventSetupPermissionlessInfrastructure) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSetupPermissionlessInfrastructure.DiscardUnknown(m)
}

var xxx_messageInfo_EventSetupPermissionlessInfrastructure proto.InternalMessageInfo

func (m *EventSetupPermissionlessInfrastructure) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EventSetupPermissionlessInfrastructure) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *EventSetupPermissionlessInfrastructure) GetMailboxId() string {
	if m != nil {
		return m.MailboxId
	}
	return ""
}

func (m *EventSetupPermissionlessInfrastructure) GetRoutingIsmId() string {
	if m != nil {
		return m.RoutingIsmId
	}
	return ""
}

func (m *EventSetupPermissionlessInfrastructure) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *EventSetupPermissionlessInfrastructure) GetLocalDomain() uint32 {
	if m != nil {
		return m.LocalDomain
	}
	return 0
}

func (m *EventSetupPermissionlessInfrastructure) GetOriginDenom() string {
	if m != nil {
		return m.OriginDenom
	}
	return ""
}

func (m *EventSetupPermissionlessInfrastructure) GetCurrentOwner() string {
	if m != nil {
		return m.CurrentOwner
	}
	return ""
}

func init() {
	proto.RegisterType((*EventSetupPermissionlessInfrastructure)(nil), "celestia.warp.v1.EventSetupPermissionlessInfrastructure")
}

func init() { proto.RegisterFile("celestia/warp/v1/events.proto", fileDescriptor_0679537d908e0877) }

var fileDescriptor_0679537d908e0877 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0xcb, 0x6e, 0xe2, 0x30,
	0x14, 0x86, 0x09, 0xc3, 0x70, 0x31, 0x30, 0x1a, 0x59, 0xb3, 0xc8, 0x8c, 0x44, 0xc4, 0x5c, 0x34,
	0x62, 0xd3, 0x44, 0x08, 0xa9, 0x0f, 0x50, 0xd1, 0x45, 0x16, 0x55, 0x2b, 0xba, 0xeb, 0x26, 0x32,
	0xc9, 0x69, 0x6a, 0x35, 0xf6, 0x89, 0x6c, 0x27, 0xd0, 0xb7, 0xe8, 0x2b, 0xf4, 0x6d, 0xba, 0x64,
	0xd9, 0x65, 0x05, 0x2f, 0x52, 0xd9, 0x81, 0xee, 0xfe, 0xf3, 0x7d, 0x7f, 0x62, 0xeb, 0x98, 0x4c,
	0x52, 0x28, 0x40, 0x1b, 0xce, 0xa2, 0x0d, 0x53, 0x65, 0x54, 0xcf, 0x23, 0xa8, 0x41, 0x1a, 0x1d,
	0x96, 0x0a, 0x0d, 0xd2, 0xef, 0x27, 0x1d, 0x5a, 0x1d, 0xd6, 0xf3, 0x5f, 0x3f, 0x72, 0xcc, 0xd1,
	0xc9, 0xc8, 0xa6, 0xa6, 0xf7, 0xe7, 0xa5, 0x4d, 0xfe, 0x5f, 0xda, 0x0f, 0x6f, 0xc1, 0x54, 0xe5,
	0x0d, 0x28, 0xc1, 0xb5, 0xe6, 0x28, 0x0b, 0xd0, 0x3a, 0x96, 0xf7, 0x8a, 0x69, 0xa3, 0xaa, 0xd4,
	0x54, 0x0a, 0xa8, 0x4f, 0x7a, 0xa9, 0x02, 0x66, 0x50, 0xf9, 0xde, 0xd4, 0x9b, 0x0d, 0x56, 0xa7,
	0x91, 0x52, 0xd2, 0x11, 0x98, 0x81, 0xdf, 0x76, 0xd8, 0x65, 0x3a, 0x21, 0x44, 0x30, 0x5e, 0xac,
	0x71, 0x9b, 0xf0, 0xcc, 0xff, 0xe2, 0xcc, 0xe0, 0x48, 0xe2, 0x8c, 0xfe, 0x23, 0xdf, 0x14, 0x56,
	0x86, 0xcb, 0x3c, 0xe1, 0x5a, 0xd8, 0x4a, 0xc7, 0x55, 0x46, 0x47, 0x1a, 0x6b, 0x11, 0x67, 0xf4,
	0x27, 0xe9, 0x1b, 0x7c, 0x04, 0x69, 0xfd, 0xd7, 0xe6, 0x4c, 0x37, 0xc7, 0x19, 0xfd, 0x4d, 0x46,
	0x05, 0xa6, 0xac, 0x48, 0x32, 0x14, 0x8c, 0x4b, 0xbf, 0x3b, 0xf5, 0x66, 0xe3, 0xd5, 0xd0, 0xb1,
	0xa5, 0x43, 0xb6, 0x82, 0x8a, 0xe7, 0x5c, 0x26, 0x19, 0x48, 0x14, 0x7e, 0xcf, 0xfd, 0x61, 0xd8,
	0xb0, 0xa5, 0x45, 0xf4, 0x2f, 0x19, 0xa7, 0x95, 0x52, 0x20, 0x4d, 0x82, 0x1b, 0x09, 0xca, 0xef,
	0x37, 0xb7, 0x38, 0xc2, 0x6b, 0xcb, 0x2e, 0xae, 0x5e, 0xf7, 0x81, 0xb7, 0xdb, 0x07, 0xde, 0xfb,
	0x3e, 0xf0, 0x9e, 0x0f, 0x41, 0x6b, 0x77, 0x08, 0x5a, 0x6f, 0x87, 0xa0, 0x75, 0xb7, 0xc8, 0xb9,
	0x79, 0xa8, 0xd6, 0x61, 0x8a, 0x22, 0x3a, 0x2d, 0x1c, 0x55, 0xfe, 0x99, 0xcf, 0x58, 0x59, 0x46,
	0xf5, 0x79, 0xb4, 0x6d, 0x1e, 0xc9, 0x3c, 0x95, 0xa0, 0xd7, 0x5d, 0xb7, 0xf9, 0xc5, 0x47, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbb, 0x55, 0x8f, 0x07, 0xc2, 0x01, 0x00, 0x00,
}

func (m *EventSetupPermissionlessInfrastructure) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSetupPermissionlessInfrastructure) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventSetupPermissionlessInfrastructure) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CurrentOwner) > 0 {
		i -= len(m.CurrentOwner)
		copy(dAtA[i:], m.CurrentOwner)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.CurrentOwner)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.OriginDenom) > 0 {
		i -= len(m.OriginDenom)
		copy(dAtA[i:], m.OriginDenom)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.OriginDenom)))
		i--
		dAtA[i] = 0x3a
	}
	if m.LocalDomain != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.LocalDomain))
		i--
		dAtA[i] = 0x30
	}
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RoutingIsmId) > 0 {
		i -= len(m.RoutingIsmId)
		copy(dAtA[i:], m.RoutingIsmId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RoutingIsmId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MailboxId) > 0 {
		i -= len(m.MailboxId)
		copy(dAtA[i:], m.MailboxId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MailboxId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Mode) > 0 {
		i -= len(m.Mode)
		copy(dAtA[i:], m.Mode)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Mode)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventSetupPermissionlessInfrastructure) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Mode)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.MailboxId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.RoutingIsmId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.LocalDomain != 0 {
		n += 1 + sovEvents(uint64(m.LocalDomain))
	}
	l = len(m.OriginDenom)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.CurrentOwner)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventSetupPermissionlessInfrastructure) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSetupPermissionlessInfrastructure: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSetupPermissionlessInfrastructure: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MailboxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MailboxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoutingIsmId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoutingIsmId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalDomain", wireType)
			}
			m.LocalDomain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LocalDomain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
