name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Nova Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Download v3 Celestia Binary
        run: curl -L -o appd/internal/testdata/celestia-app_Linux_x86_64.tar.gz https://github.com/celestiaorg/celestia-app/releases/download/v3.4.0/celestia-app_Linux_x86_64.tar.gz

      - name: Run Tests
        run: make test-cover
