pull_request_rules:
  - name: backport patches to v1.x branch
    conditions:
      - base=main
      - label=backport:v1.x
    actions:
      backport:
        branches:
          - v1.x
  - name: backport patches to v2.x branch
    conditions:
      - base=main
      - label=backport:v2.x
    actions:
      backport:
        branches:
          - v2.x
  - name: backport patches to v3.x branch
    conditions:
      - base=main
      - label=backport:v3.x
    actions:
      backport:
        branches:
          - v3.x
  - name: backport patches to v4.x branch
    conditions:
      - base=main
      - label=backport:v4.x
    actions:
      backport:
        branches:
          - v4.x
  - name: forward-port patches to main branch (v1.x)
    conditions:
      - base=v1.x
      - label=forwardport:main
    actions:
      backport:
        branches:
          - main
  - name: forward-port patches to main branch (v2.x)
    conditions:
      - base=v2.x
      - label=forwardport:main
    actions:
      backport:
        branches:
          - main
