run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - exportloopref
    - gofumpt
    - misspell
    - nakedret
    - revive
    - prealloc
    - stylecheck
    - unconvert
    - gocritic

  disable:
    - staticcheck

linters-settings:
  nakedret:
    # Ban the use of naked returns because they reduce code readability.
    max-func-lines: 0 # override the default: 30
