# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# NOTE: CGO is required for ledger support to work, however goreleaser
# technically doesn't support CGO. But it seems to work so that's cool. This
# only seems to work because we are building for a single binary. Cross
# compiling binaries for multiple distributions doesn't work and a proper
# workaround will be needed.
#
# REF: https://goreleaser.com/limitations/cgo/

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/celestia-appd
    binary: celestia-appd
    env:
      - SDKPath={{ "github.com/cosmos/cosmos-sdk/version" }}
    goarch:
      - amd64
    goos:
      - linux
    tags:
      - ledger
    ldflags:
      # Ref: https://goreleaser.com/customization/templates/#common-fields
      #
      # .FullCommit is git commit hash goreleaser is using for the release
      #
      # .Version is the version being released
      - -X "{{ .Env.SDKPath }}.Name=celestia-app"
      - -X "{{ .Env.SDKPath }}.AppName=celestia-appd"
      - -X "{{ .Env.SDKPath }}.Version={{ .Version }}"
      - -X "{{ .Env.SDKPath }}.Commit={{ .FullCommit }}"
dist: ./build/goreleaser
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of
    # uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
