# Ledger support is only available if the binary is built with CGO enabled.
# Since GoReleaser doesn't support CGO natively, our GoReleaser process builds
# binaries in a Docker image maintained by goreleaser-cross that has CGO support
# for multiple platforms. See https://github.com/goreleaser/goreleaser-cross

version: 2
before:
  hooks:
    - go mod tidy
    # These hooks get run once. We want to explicitly download every embedded binary so we can build the multiplexer
    # for every architecture. These versions must be updated at the same time as the version in the Makefile.
    - ./scripts/download_binary.sh celestia-app_Darwin_arm64.tar.gz celestia-app_darwin_v3_arm64.tar.gz v3.10.6
    - ./scripts/download_binary.sh celestia-app_Linux_arm64.tar.gz celestia-app_linux_v3_arm64.tar.gz v3.10.6
    - ./scripts/download_binary.sh celestia-app_Darwin_x86_64.tar.gz celestia-app_darwin_v3_amd64.tar.gz v3.10.6
    - ./scripts/download_binary.sh celestia-app_Linux_x86_64.tar.gz celestia-app_linux_v3_amd64.tar.gz v3.10.6
    - ./scripts/download_binary.sh celestia-app-standalone_Darwin_arm64.tar.gz celestia-app_darwin_v4_arm64.tar.gz v4.1.0
    - ./scripts/download_binary.sh celestia-app-standalone_Linux_arm64.tar.gz celestia-app_linux_v4_arm64.tar.gz v4.1.0
    - ./scripts/download_binary.sh celestia-app-standalone_Darwin_x86_64.tar.gz celestia-app_darwin_v4_amd64.tar.gz v4.1.0
    - ./scripts/download_binary.sh celestia-app-standalone_Linux_x86_64.tar.gz celestia-app_linux_v4_amd64.tar.gz v4.1.0
    - ./scripts/download_binary.sh celestia-app-standalone_Darwin_arm64.tar.gz celestia-app_darwin_v5_arm64.tar.gz v5.0.4-rc0
    - ./scripts/download_binary.sh celestia-app-standalone_Linux_arm64.tar.gz celestia-app_linux_v5_arm64.tar.gz v5.0.4-rc0
    - ./scripts/download_binary.sh celestia-app-standalone_Darwin_x86_64.tar.gz celestia-app_darwin_v5_amd64.tar.gz v5.0.4-rc0
    - ./scripts/download_binary.sh celestia-app-standalone_Linux_x86_64.tar.gz celestia-app_linux_v5_amd64.tar.gz v5.0.4-rc0

builds:
  - id: darwin-amd64-multiplexer
    main: ./cmd/celestia-appd
    binary: celestia-appd
    env:
      - SDKPath={{ "github.com/cosmos/cosmos-sdk/version" }}
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goarch:
      - amd64
    goos:
      - darwin
    tags:
      - ledger
      - multiplexer
    ldflags:
      # Ref: https://goreleaser.com/customization/templates/#common-fields
      # .Version is the version being released
      # .FullCommit is git commit hash goreleaser is using for the release
      - -X "{{ .Env.SDKPath }}.Name=celestia-app"
      - -X "{{ .Env.SDKPath }}.AppName=celestia-appd"
      - -X "{{ .Env.SDKPath }}.Version={{ .Version }}"
      - -X "{{ .Env.SDKPath }}.Commit={{ .FullCommit }}"
  - id: darwin-arm64-multiplexer
    main: ./cmd/celestia-appd
    binary: celestia-appd
    env:
      - SDKPath={{ "github.com/cosmos/cosmos-sdk/version" }}
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goarch:
      - arm64
    goos:
      - darwin
    tags:
      - ledger
      - multiplexer
    ldflags:
      # Ref: https://goreleaser.com/customization/templates/#common-fields
      # .Version is the version being released
      # .FullCommit is git commit hash goreleaser is using for the release
      - -X "{{ .Env.SDKPath }}.Name=celestia-app"
      - -X "{{ .Env.SDKPath }}.AppName=celestia-appd"
      - -X "{{ .Env.SDKPath }}.Version={{ .Version }}"
      - -X "{{ .Env.SDKPath }}.Commit={{ .FullCommit }}"
  - id: linux-amd64-multiplexer
    main: ./cmd/celestia-appd
    binary: celestia-appd
    env:
      - SDKPath={{ "github.com/cosmos/cosmos-sdk/version" }}
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    tags:
      - ledger
      - multiplexer
    ldflags:
      # Ref: https://goreleaser.com/customization/templates/#common-fields
      # .Version is the version being released
      # .FullCommit is git commit hash goreleaser is using for the release
      - -X "{{ .Env.SDKPath }}.Name=celestia-app"
      - -X "{{ .Env.SDKPath }}.AppName=celestia-appd"
      - -X "{{ .Env.SDKPath }}.Version={{ .Version }}"
      - -X "{{ .Env.SDKPath }}.Commit={{ .FullCommit }}"
  - id: linux-arm64-multiplexer
    main: ./cmd/celestia-appd
    binary: celestia-appd
    env:
      - SDKPath={{ "github.com/cosmos/cosmos-sdk/version" }}
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goarch:
      - arm64
    goos:
      - linux
    tags:
      - ledger
      - multiplexer
    ldflags:
      # Ref: https://goreleaser.com/customization/templates/#common-fields
      # .Version is the version being released
      # .FullCommit is git commit hash goreleaser is using for the release
      - -X "{{ .Env.SDKPath }}.Name=celestia-app"
      - -X "{{ .Env.SDKPath }}.AppName=celestia-appd"
      - -X "{{ .Env.SDKPath }}.Version={{ .Version }}"
      - -X "{{ .Env.SDKPath }}.Commit={{ .FullCommit }}"
  - id: darwin-amd64
    main: ./cmd/celestia-appd
    binary: celestia-appd
    env:
      - SDKPath={{ "github.com/cosmos/cosmos-sdk/version" }}
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goarch:
      - amd64
    goos:
      - darwin
    tags:
      - ledger
    ldflags:
      # Ref: https://goreleaser.com/customization/templates/#common-fields
      # .Version is the version being released
      # .FullCommit is git commit hash goreleaser is using for the release
      - -X "{{ .Env.SDKPath }}.Name=celestia-app"
      - -X "{{ .Env.SDKPath }}.AppName=celestia-appd"
      - -X "{{ .Env.SDKPath }}.Version={{ .Version }}"
      - -X "{{ .Env.SDKPath }}.Commit={{ .FullCommit }}"
  - id: darwin-arm64
    main: ./cmd/celestia-appd
    binary: celestia-appd
    env:
      - SDKPath={{ "github.com/cosmos/cosmos-sdk/version" }}
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goarch:
      - arm64
    goos:
      - darwin
    tags:
      - ledger
    ldflags:
      # Ref: https://goreleaser.com/customization/templates/#common-fields
      # .Version is the version being released
      # .FullCommit is git commit hash goreleaser is using for the release
      - -X "{{ .Env.SDKPath }}.Name=celestia-app"
      - -X "{{ .Env.SDKPath }}.AppName=celestia-appd"
      - -X "{{ .Env.SDKPath }}.Version={{ .Version }}"
      - -X "{{ .Env.SDKPath }}.Commit={{ .FullCommit }}"
  - id: linux-amd64
    main: ./cmd/celestia-appd
    binary: celestia-appd
    env:
      - SDKPath={{ "github.com/cosmos/cosmos-sdk/version" }}
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    tags:
      - ledger
    ldflags:
      # Ref: https://goreleaser.com/customization/templates/#common-fields
      # .Version is the version being released
      # .FullCommit is git commit hash goreleaser is using for the release
      - -X "{{ .Env.SDKPath }}.Name=celestia-app"
      - -X "{{ .Env.SDKPath }}.AppName=celestia-appd"
      - -X "{{ .Env.SDKPath }}.Version={{ .Version }}"
      - -X "{{ .Env.SDKPath }}.Commit={{ .FullCommit }}"
  - id: linux-arm64
    main: ./cmd/celestia-appd
    binary: celestia-appd
    env:
      - SDKPath={{ "github.com/cosmos/cosmos-sdk/version" }}
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goarch:
      - arm64
    goos:
      - linux
    tags:
      - ledger
    ldflags:
      # Ref: https://goreleaser.com/customization/templates/#common-fields
      # .Version is the version being released
      # .FullCommit is git commit hash goreleaser is using for the release
      - -X "{{ .Env.SDKPath }}.Name=celestia-app"
      - -X "{{ .Env.SDKPath }}.AppName=celestia-appd"
      - -X "{{ .Env.SDKPath }}.Version={{ .Version }}"
      - -X "{{ .Env.SDKPath }}.Commit={{ .FullCommit }}"
dist: ./build/goreleaser
archives:
  - id: multiplexer
    ids:
      - darwin-amd64-multiplexer
      - darwin-arm64-multiplexer
      - linux-amd64-multiplexer
      - linux-arm64-multiplexer
    formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: standalone
    ids:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
      - linux-arm64
    formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of
    # uname.
    name_template: >-
      {{ .ProjectName }}-standalone_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: auto
git:
  prerelease_suffix: "-"
