---
services:
  validator:
    ports: !override
      - '127.0.0.1::26657'
      - '127.0.0.1::1317'
      - '127.0.0.1::9090'
      - '127.0.0.1::7980'
  bridge:
    ports: !override
      - '127.0.0.1::26658'
