// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/forwarding/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryDeriveForwardingAddressRequest is the request for DeriveForwardingAddress.
type QueryDeriveForwardingAddressRequest struct {
	// dest_domain is the destination chain domain ID.
	DestDomain uint32 `protobuf:"varint,1,opt,name=dest_domain,json=destDomain,proto3" json:"dest_domain,omitempty"`
	// dest_recipient is the recipient on destination chain (32 bytes, hex-encoded, 0x prefix optional).
	DestRecipient string `protobuf:"bytes,2,opt,name=dest_recipient,json=destRecipient,proto3" json:"dest_recipient,omitempty"`
	// token_id is the Hyperlane token identifier to bind this forwarding address to.
	TokenId string `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// custom_hook_id optionally binds this forwarding address to a specific
	// post-dispatch hook (e.g. an alternative IGP). Hex-encoded (0x prefix optional).
	// When set, the resulting address can only be forwarded through that exact hook.
	// Empty or the zero address => an address that uses the mailbox default hook.
	CustomHookId string `protobuf:"bytes,4,opt,name=custom_hook_id,json=customHookId,proto3" json:"custom_hook_id,omitempty"`
}

func (m *QueryDeriveForwardingAddressRequest) Reset()         { *m = QueryDeriveForwardingAddressRequest{} }
func (m *QueryDeriveForwardingAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDeriveForwardingAddressRequest) ProtoMessage()    {}
func (*QueryDeriveForwardingAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a1be30426bc9f30, []int{0}
}
func (m *QueryDeriveForwardingAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDeriveForwardingAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDeriveForwardingAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDeriveForwardingAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeriveForwardingAddressRequest.Merge(m, src)
}
func (m *QueryDeriveForwardingAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDeriveForwardingAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeriveForwardingAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeriveForwardingAddressRequest proto.InternalMessageInfo

func (m *QueryDeriveForwardingAddressRequest) GetDestDomain() uint32 {
	if m != nil {
		return m.DestDomain
	}
	return 0
}

func (m *QueryDeriveForwardingAddressRequest) GetDestRecipient() string {
	if m != nil {
		return m.DestRecipient
	}
	return ""
}

func (m *QueryDeriveForwardingAddressRequest) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *QueryDeriveForwardingAddressRequest) GetCustomHookId() string {
	if m != nil {
		return m.CustomHookId
	}
	return ""
}

// QueryDeriveForwardingAddressResponse is the response for DeriveForwardingAddress.
type QueryDeriveForwardingAddressResponse struct {
	// address is the derived forwarding address (bech32).
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryDeriveForwardingAddressResponse) Reset()         { *m = QueryDeriveForwardingAddressResponse{} }
func (m *QueryDeriveForwardingAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDeriveForwardingAddressResponse) ProtoMessage()    {}
func (*QueryDeriveForwardingAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a1be30426bc9f30, []int{1}
}
func (m *QueryDeriveForwardingAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDeriveForwardingAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDeriveForwardingAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDeriveForwardingAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeriveForwardingAddressResponse.Merge(m, src)
}
func (m *QueryDeriveForwardingAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDeriveForwardingAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeriveForwardingAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeriveForwardingAddressResponse proto.InternalMessageInfo

func (m *QueryDeriveForwardingAddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryQuoteForwardingFeeRequest is the request for QuoteForwardingFee.
type QueryQuoteForwardingFeeRequest struct {
	// dest_domain is the destination chain domain ID.
	DestDomain uint32 `protobuf:"varint,1,opt,name=dest_domain,json=destDomain,proto3" json:"dest_domain,omitempty"`
	// token_id is the Hyperlane token identifier to quote fees for.
	TokenId string `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// custom_hook_id optionally selects the post-dispatch hook (e.g. an alternative
	// IGP) the forward will be routed through, so the quote reflects that hook's
	// price rather than the mailbox default. Hex-encoded (0x prefix optional).
	// Empty => quote against the mailbox default hook (unchanged behavior).
	CustomHookId string `protobuf:"bytes,3,opt,name=custom_hook_id,json=customHookId,proto3" json:"custom_hook_id,omitempty"`
	// custom_hook_metadata is optional hex-encoded metadata passed to the custom
	// hook. Some hooks price the dispatch off this metadata, so it must match the
	// custom_hook_metadata used in MsgForward for the quote to reflect the fee that
	// will actually be charged. Ignored by hooks that do not price off metadata
	// (e.g. the default IGP).
	CustomHookMetadata string `protobuf:"bytes,4,opt,name=custom_hook_metadata,json=customHookMetadata,proto3" json:"custom_hook_metadata,omitempty"`
}

func (m *QueryQuoteForwardingFeeRequest) Reset()         { *m = QueryQuoteForwardingFeeRequest{} }
func (m *QueryQuoteForwardingFeeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryQuoteForwardingFeeRequest) ProtoMessage()    {}
func (*QueryQuoteForwardingFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a1be30426bc9f30, []int{2}
}
func (m *QueryQuoteForwardingFeeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryQuoteForwardingFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryQuoteForwardingFeeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryQuoteForwardingFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQuoteForwardingFeeRequest.Merge(m, src)
}
func (m *QueryQuoteForwardingFeeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryQuoteForwardingFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQuoteForwardingFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQuoteForwardingFeeRequest proto.InternalMessageInfo

func (m *QueryQuoteForwardingFeeRequest) GetDestDomain() uint32 {
	if m != nil {
		return m.DestDomain
	}
	return 0
}

func (m *QueryQuoteForwardingFeeRequest) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *QueryQuoteForwardingFeeRequest) GetCustomHookId() string {
	if m != nil {
		return m.CustomHookId
	}
	return ""
}

func (m *QueryQuoteForwardingFeeRequest) GetCustomHookMetadata() string {
	if m != nil {
		return m.CustomHookMetadata
	}
	return ""
}

// QueryQuoteForwardingFeeResponse is the response for QuoteForwardingFee.
type QueryQuoteForwardingFeeResponse struct {
	// fee is the estimated Hyperlane IGP fee required for forwarding.
	// Relayers should set max_igp_fee >= this value (with some buffer for price changes).
	Fee types.Coin `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee"`
}

func (m *QueryQuoteForwardingFeeResponse) Reset()         { *m = QueryQuoteForwardingFeeResponse{} }
func (m *QueryQuoteForwardingFeeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryQuoteForwardingFeeResponse) ProtoMessage()    {}
func (*QueryQuoteForwardingFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a1be30426bc9f30, []int{3}
}
func (m *QueryQuoteForwardingFeeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryQuoteForwardingFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryQuoteForwardingFeeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryQuoteForwardingFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQuoteForwardingFeeResponse.Merge(m, src)
}
func (m *QueryQuoteForwardingFeeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryQuoteForwardingFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQuoteForwardingFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQuoteForwardingFeeResponse proto.InternalMessageInfo

func (m *QueryQuoteForwardingFeeResponse) GetFee() types.Coin {
	if m != nil {
		return m.Fee
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*QueryDeriveForwardingAddressRequest)(nil), "celestia.forwarding.v1.QueryDeriveForwardingAddressRequest")
	proto.RegisterType((*QueryDeriveForwardingAddressResponse)(nil), "celestia.forwarding.v1.QueryDeriveForwardingAddressResponse")
	proto.RegisterType((*QueryQuoteForwardingFeeRequest)(nil), "celestia.forwarding.v1.QueryQuoteForwardingFeeRequest")
	proto.RegisterType((*QueryQuoteForwardingFeeResponse)(nil), "celestia.forwarding.v1.QueryQuoteForwardingFeeResponse")
}

func init() {
	proto.RegisterFile("celestia/forwarding/v1/query.proto", fileDescriptor_9a1be30426bc9f30)
}

var fileDescriptor_9a1be30426bc9f30 = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0x4f, 0x13, 0x4f,
	0x14, 0xee, 0x52, 0x7e, 0x3f, 0x64, 0x10, 0x0e, 0x13, 0xa2, 0xa5, 0x31, 0x5b, 0xb2, 0x62, 0xc2,
	0x85, 0x1d, 0x5b, 0x13, 0x4c, 0x94, 0x8b, 0x95, 0x10, 0x39, 0x98, 0xc0, 0xea, 0xc1, 0x70, 0xd9,
	0x4c, 0x77, 0x5f, 0x97, 0x49, 0xe9, 0xbe, 0x65, 0x67, 0x5a, 0x25, 0x84, 0x8b, 0x7f, 0x81, 0x89,
	0xff, 0x87, 0x27, 0xfe, 0x04, 0x0f, 0x78, 0x23, 0x7a, 0xf1, 0x64, 0x4c, 0xeb, 0xd9, 0xbf, 0xc1,
	0xec, 0xec, 0xb4, 0x34, 0xc1, 0x45, 0xf4, 0xb6, 0xef, 0x9b, 0xef, 0xbd, 0x7e, 0xdf, 0x37, 0xaf,
	0x43, 0x9c, 0x00, 0x0e, 0x40, 0x2a, 0xc1, 0x59, 0x1b, 0xd3, 0xd7, 0x3c, 0x0d, 0x45, 0x1c, 0xb1,
	0x7e, 0x9d, 0x1d, 0xf6, 0x20, 0x3d, 0x72, 0x93, 0x14, 0x15, 0xd2, 0x5b, 0x23, 0x8e, 0x7b, 0xc1,
	0x71, 0xfb, 0xf5, 0xaa, 0x1d, 0xa0, 0xec, 0xa2, 0x64, 0x2d, 0x2e, 0x81, 0xf5, 0xeb, 0x2d, 0x50,
	0xbc, 0xce, 0x02, 0x14, 0x71, 0xde, 0x57, 0x5d, 0xca, 0xcf, 0x7d, 0x5d, 0xb1, 0xbc, 0x30, 0x47,
	0x8b, 0x11, 0x46, 0x98, 0xe3, 0xd9, 0x97, 0x41, 0xef, 0x44, 0x88, 0xd1, 0x01, 0x30, 0x9e, 0x08,
	0xc6, 0xe3, 0x18, 0x15, 0x57, 0x02, 0x63, 0xd3, 0xe3, 0x7c, 0xb0, 0xc8, 0xdd, 0xdd, 0x4c, 0xd6,
	0x26, 0xa4, 0xa2, 0x0f, 0x5b, 0x63, 0x2d, 0x4f, 0xc2, 0x30, 0x05, 0x29, 0x3d, 0x38, 0xec, 0x81,
	0x54, 0xb4, 0x46, 0xe6, 0x42, 0x90, 0xca, 0x0f, 0xb1, 0xcb, 0x45, 0x5c, 0xb1, 0x96, 0xad, 0xd5,
	0x79, 0x8f, 0x64, 0xd0, 0xa6, 0x46, 0xe8, 0x3d, 0xb2, 0xa0, 0x09, 0x29, 0x04, 0x22, 0x11, 0x10,
	0xab, 0xca, 0xd4, 0xb2, 0xb5, 0x3a, 0xeb, 0xcd, 0x67, 0xa8, 0x37, 0x02, 0xe9, 0x12, 0xb9, 0xa1,
	0xb0, 0x03, 0xb1, 0x2f, 0xc2, 0x4a, 0x59, 0x13, 0x66, 0x74, 0xbd, 0x1d, 0xd2, 0x15, 0xb2, 0x10,
	0xf4, 0xa4, 0xc2, 0xae, 0xbf, 0x8f, 0xd8, 0xc9, 0x08, 0xd3, 0x9a, 0x70, 0x33, 0x47, 0x9f, 0x21,
	0x76, 0xb6, 0x43, 0x67, 0x8f, 0xac, 0x5c, 0xad, 0x57, 0x26, 0x18, 0x4b, 0xa0, 0x0d, 0x32, 0xc3,
	0x73, 0x48, 0x8b, 0x9d, 0x6d, 0x56, 0x3e, 0x9f, 0xae, 0x2d, 0x9a, 0xbc, 0x0c, 0xf9, 0x85, 0x4a,
	0x45, 0x1c, 0x79, 0x23, 0xa2, 0x73, 0x6a, 0x11, 0x5b, 0x0f, 0xdf, 0xed, 0xa1, 0x9a, 0x98, 0xbd,
	0x05, 0x70, 0xed, 0x1c, 0x26, 0x0d, 0x4e, 0xfd, 0xc9, 0x60, 0xf9, 0xb2, 0x41, 0x7a, 0x9f, 0x2c,
	0x4e, 0xb2, 0xba, 0xa0, 0x78, 0xc8, 0x15, 0x37, 0x61, 0xd0, 0x0b, 0xee, 0x73, 0x73, 0xe2, 0xbc,
	0x24, 0xb5, 0x42, 0xd5, 0x26, 0x8d, 0x3a, 0x29, 0xb7, 0x01, 0xb4, 0xdc, 0xb9, 0xc6, 0x92, 0x6b,
	0x62, 0xc8, 0x76, 0xcc, 0x35, 0x3b, 0xe6, 0x3e, 0x45, 0x11, 0x37, 0xa7, 0xcf, 0xbe, 0xd5, 0x4a,
	0x5e, 0xc6, 0x6d, 0x7c, 0x2c, 0x93, 0xff, 0xf4, 0x58, 0xfa, 0xd3, 0x22, 0xb7, 0x0b, 0xe2, 0xa6,
	0x8f, 0xdd, 0xdf, 0xef, 0xb1, 0x7b, 0x8d, 0xa5, 0xaa, 0x6e, 0xfc, 0x5b, 0x73, 0xee, 0xc9, 0x79,
	0xf5, 0xf6, 0xcb, 0x8f, 0xf7, 0x53, 0x1e, 0xdd, 0x61, 0x05, 0x7f, 0xb7, 0x50, 0x0f, 0xf0, 0xcd,
	0xed, 0xb2, 0xe3, 0xd1, 0xbd, 0x9c, 0xb0, 0xe3, 0x89, 0x3b, 0x1c, 0x55, 0xe3, 0xc5, 0x3d, 0xa1,
	0x9f, 0x2c, 0x42, 0x2f, 0x87, 0x49, 0xd7, 0xaf, 0x94, 0x5b, 0xb8, 0x33, 0xd5, 0x87, 0x7f, 0xdd,
	0x67, 0x1c, 0x36, 0xb5, 0xc3, 0x0d, 0xfa, 0x88, 0x15, 0x3e, 0x28, 0xa8, 0xc0, 0x6f, 0x03, 0x14,
	0x9a, 0x6b, 0xee, 0x9c, 0x0d, 0x6c, 0xeb, 0x7c, 0x60, 0x5b, 0xdf, 0x07, 0xb6, 0xf5, 0x6e, 0x68,
	0x97, 0xce, 0x87, 0x76, 0xe9, 0xeb, 0xd0, 0x2e, 0xed, 0xad, 0x47, 0x42, 0xed, 0xf7, 0x5a, 0x6e,
	0x80, 0xdd, 0xf1, 0x7c, 0x4c, 0xa3, 0xf1, 0xf7, 0x1a, 0x4f, 0x12, 0xf6, 0x66, 0xf2, 0x17, 0xd5,
	0x51, 0x02, 0xb2, 0xf5, 0xbf, 0x7e, 0x39, 0x1e, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xa9,
	0x40, 0x7d, 0xe6, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// DeriveForwardingAddress derives the forwarding address for given parameters.
	DeriveForwardingAddress(ctx context.Context, in *QueryDeriveForwardingAddressRequest, opts ...grpc.CallOption) (*QueryDeriveForwardingAddressResponse, error)
	// QuoteForwardingFee returns the estimated Hyperlane IGP fee for forwarding to a destination.
	// Relayers should query this before submitting MsgForward to determine the required max_igp_fee.
	QuoteForwardingFee(ctx context.Context, in *QueryQuoteForwardingFeeRequest, opts ...grpc.CallOption) (*QueryQuoteForwardingFeeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) DeriveForwardingAddress(ctx context.Context, in *QueryDeriveForwardingAddressRequest, opts ...grpc.CallOption) (*QueryDeriveForwardingAddressResponse, error) {
	out := new(QueryDeriveForwardingAddressResponse)
	err := c.cc.Invoke(ctx, "/celestia.forwarding.v1.Query/DeriveForwardingAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QuoteForwardingFee(ctx context.Context, in *QueryQuoteForwardingFeeRequest, opts ...grpc.CallOption) (*QueryQuoteForwardingFeeResponse, error) {
	out := new(QueryQuoteForwardingFeeResponse)
	err := c.cc.Invoke(ctx, "/celestia.forwarding.v1.Query/QuoteForwardingFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// DeriveForwardingAddress derives the forwarding address for given parameters.
	DeriveForwardingAddress(context.Context, *QueryDeriveForwardingAddressRequest) (*QueryDeriveForwardingAddressResponse, error)
	// QuoteForwardingFee returns the estimated Hyperlane IGP fee for forwarding to a destination.
	// Relayers should query this before submitting MsgForward to determine the required max_igp_fee.
	QuoteForwardingFee(context.Context, *QueryQuoteForwardingFeeRequest) (*QueryQuoteForwardingFeeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) DeriveForwardingAddress(ctx context.Context, req *QueryDeriveForwardingAddressRequest) (*QueryDeriveForwardingAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeriveForwardingAddress not implemented")
}
func (*UnimplementedQueryServer) QuoteForwardingFee(ctx context.Context, req *QueryQuoteForwardingFeeRequest) (*QueryQuoteForwardingFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteForwardingFee not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_DeriveForwardingAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDeriveForwardingAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DeriveForwardingAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celestia.forwarding.v1.Query/DeriveForwardingAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DeriveForwardingAddress(ctx, req.(*QueryDeriveForwardingAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QuoteForwardingFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryQuoteForwardingFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QuoteForwardingFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celestia.forwarding.v1.Query/QuoteForwardingFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QuoteForwardingFee(ctx, req.(*QueryQuoteForwardingFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "celestia.forwarding.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeriveForwardingAddress",
			Handler:    _Query_DeriveForwardingAddress_Handler,
		},
		{
			MethodName: "QuoteForwardingFee",
			Handler:    _Query_QuoteForwardingFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "celestia/forwarding/v1/query.proto",
}

func (m *QueryDeriveForwardingAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDeriveForwardingAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDeriveForwardingAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CustomHookId) > 0 {
		i -= len(m.CustomHookId)
		copy(dAtA[i:], m.CustomHookId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CustomHookId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DestRecipient) > 0 {
		i -= len(m.DestRecipient)
		copy(dAtA[i:], m.DestRecipient)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DestRecipient)))
		i--
		dAtA[i] = 0x12
	}
	if m.DestDomain != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.DestDomain))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryDeriveForwardingAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDeriveForwardingAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDeriveForwardingAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryQuoteForwardingFeeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryQuoteForwardingFeeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryQuoteForwardingFeeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CustomHookMetadata) > 0 {
		i -= len(m.CustomHookMetadata)
		copy(dAtA[i:], m.CustomHookMetadata)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CustomHookMetadata)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CustomHookId) > 0 {
		i -= len(m.CustomHookId)
		copy(dAtA[i:], m.CustomHookId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CustomHookId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0x12
	}
	if m.DestDomain != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.DestDomain))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryQuoteForwardingFeeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryQuoteForwardingFeeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryQuoteForwardingFeeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryDeriveForwardingAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DestDomain != 0 {
		n += 1 + sovQuery(uint64(m.DestDomain))
	}
	l = len(m.DestRecipient)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.CustomHookId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDeriveForwardingAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryQuoteForwardingFeeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DestDomain != 0 {
		n += 1 + sovQuery(uint64(m.DestDomain))
	}
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.CustomHookId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.CustomHookMetadata)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryQuoteForwardingFeeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Fee.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryDeriveForwardingAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDeriveForwardingAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDeriveForwardingAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestDomain", wireType)
			}
			m.DestDomain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestDomain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestRecipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestRecipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomHookId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CustomHookId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDeriveForwardingAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDeriveForwardingAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDeriveForwardingAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryQuoteForwardingFeeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryQuoteForwardingFeeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryQuoteForwardingFeeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestDomain", wireType)
			}
			m.DestDomain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestDomain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomHookId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CustomHookId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomHookMetadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CustomHookMetadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryQuoteForwardingFeeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryQuoteForwardingFeeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryQuoteForwardingFeeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
