// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/feeaddress/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgForwardFees is a protocol-injected message that forwards accumulated
// tokens from the fee address to the fee collector. This message is special:
// - It is injected by PrepareProposal when fee address has balance
// - The transaction fee equals the fee address balance
// - ProcessProposal enforces that this tx must be present if fee address has balance
// - Validation happens via ProcessProposal checking tx fee == fee address balance
// - FeeForwardTerminatorDecorator terminates ante chain early, skipping signature verification
type MsgForwardFees struct {
	// from_address is the fee address from which tokens are forwarded.
	// This is always set to the well-known fee address (FeeAddressBech32).
	// Note: Although this field specifies a signer, signature verification is
	// skipped because FeeForwardTerminatorDecorator terminates the ante chain
	// before signature-related decorators run.
	FromAddress string `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
}

func (m *MsgForwardFees) Reset()         { *m = MsgForwardFees{} }
func (m *MsgForwardFees) String() string { return proto.CompactTextString(m) }
func (*MsgForwardFees) ProtoMessage()    {}
func (*MsgForwardFees) Descriptor() ([]byte, []int) {
	return fileDescriptor_7123d30f9b490d42, []int{0}
}
func (m *MsgForwardFees) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgForwardFees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgForwardFees.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgForwardFees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgForwardFees.Merge(m, src)
}
func (m *MsgForwardFees) XXX_Size() int {
	return m.Size()
}
func (m *MsgForwardFees) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgForwardFees.DiscardUnknown(m)
}

var xxx_messageInfo_MsgForwardFees proto.InternalMessageInfo

func (m *MsgForwardFees) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

// MsgForwardFeesResponse is the response type for the ForwardFees RPC.
type MsgForwardFeesResponse struct {
}

func (m *MsgForwardFeesResponse) Reset()         { *m = MsgForwardFeesResponse{} }
func (m *MsgForwardFeesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgForwardFeesResponse) ProtoMessage()    {}
func (*MsgForwardFeesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7123d30f9b490d42, []int{1}
}
func (m *MsgForwardFeesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgForwardFeesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgForwardFeesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgForwardFeesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgForwardFeesResponse.Merge(m, src)
}
func (m *MsgForwardFeesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgForwardFeesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgForwardFeesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgForwardFeesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgForwardFees)(nil), "celestia.feeaddress.v1.MsgForwardFees")
	proto.RegisterType((*MsgForwardFeesResponse)(nil), "celestia.feeaddress.v1.MsgForwardFeesResponse")
}

func init() { proto.RegisterFile("celestia/feeaddress/v1/tx.proto", fileDescriptor_7123d30f9b490d42) }

var fileDescriptor_7123d30f9b490d42 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0x4e, 0xcd, 0x49,
	0x2d, 0x2e, 0xc9, 0x4c, 0xd4, 0x4f, 0x4b, 0x4d, 0x4d, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0xd6,
	0x2f, 0x33, 0xd4, 0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x83, 0x29, 0xd0,
	0x43, 0x28, 0xd0, 0x2b, 0x33, 0x94, 0x12, 0x4f, 0xce, 0x2f, 0xce, 0xcd, 0x2f, 0xd6, 0xcf, 0x2d,
	0x4e, 0x07, 0xa9, 0xcf, 0x2d, 0x4e, 0x87, 0x68, 0x90, 0x92, 0x84, 0x48, 0xc4, 0x83, 0x79, 0xfa,
	0x10, 0x0e, 0x44, 0x4a, 0x29, 0x81, 0x8b, 0xcf, 0xb7, 0x38, 0xdd, 0x2d, 0xbf, 0xa8, 0x3c, 0xb1,
	0x28, 0xc5, 0x2d, 0x35, 0xb5, 0x58, 0xc8, 0x9a, 0x8b, 0x27, 0xad, 0x28, 0x3f, 0x37, 0x1e, 0x6a,
	0xb0, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xa7, 0x93, 0xc4, 0xa5, 0x2d, 0xba, 0x22, 0x50, 0x9d, 0x8e,
	0x10, 0x99, 0xe0, 0x92, 0xa2, 0xcc, 0xbc, 0xf4, 0x20, 0x6e, 0x90, 0x6a, 0xa8, 0x90, 0x95, 0x60,
	0xd3, 0xf3, 0x0d, 0x5a, 0x28, 0xfa, 0x95, 0x24, 0xb8, 0xc4, 0x50, 0x6d, 0x08, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0x35, 0x2a, 0xe6, 0x62, 0xf6, 0x2d, 0x4e, 0x17, 0x4a, 0xe5, 0xe2, 0x46,
	0xb6, 0x5f, 0x4d, 0x0f, 0xbb, 0xf7, 0xf4, 0x50, 0x4d, 0x91, 0xd2, 0x23, 0x4e, 0x1d, 0xcc, 0x36,
	0x29, 0xd6, 0x86, 0xe7, 0x1b, 0xb4, 0x18, 0x9d, 0x02, 0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48,
	0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1,
	0x58, 0x8e, 0x21, 0xca, 0x2c, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f,
	0x66, 0x74, 0x7e, 0x51, 0x3a, 0x9c, 0xad, 0x9b, 0x58, 0x50, 0xa0, 0x5f, 0x81, 0x1c, 0x29, 0x25,
	0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c, 0xe0, 0x90, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc7,
	0x28, 0x80, 0xba, 0xb8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ForwardFees is a protocol-injected transaction that forwards accumulated
	// tokens from the fee address to the fee collector. These fees are then
	// distributed to validators as block rewards via the standard distribution
	// module. This message has no signer - it is injected by the block proposer
	// in PrepareProposal and validated in ProcessProposal.
	//
	// Note: This RPC intentionally has no google.api.http annotation because it
	// is a protocol-injected message that should not be callable via REST API.
	// If an EOA or any user attempts to submit this message directly, it is
	// rejected in CheckTx with: "MsgForwardFees cannot be submitted by users;
	// it is protocol-injected only" (see FeeForwardDecorator in ante handler).
	ForwardFees(ctx context.Context, in *MsgForwardFees, opts ...grpc.CallOption) (*MsgForwardFeesResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ForwardFees(ctx context.Context, in *MsgForwardFees, opts ...grpc.CallOption) (*MsgForwardFeesResponse, error) {
	out := new(MsgForwardFeesResponse)
	err := c.cc.Invoke(ctx, "/celestia.feeaddress.v1.Msg/ForwardFees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ForwardFees is a protocol-injected transaction that forwards accumulated
	// tokens from the fee address to the fee collector. These fees are then
	// distributed to validators as block rewards via the standard distribution
	// module. This message has no signer - it is injected by the block proposer
	// in PrepareProposal and validated in ProcessProposal.
	//
	// Note: This RPC intentionally has no google.api.http annotation because it
	// is a protocol-injected message that should not be callable via REST API.
	// If an EOA or any user attempts to submit this message directly, it is
	// rejected in CheckTx with: "MsgForwardFees cannot be submitted by users;
	// it is protocol-injected only" (see FeeForwardDecorator in ante handler).
	ForwardFees(context.Context, *MsgForwardFees) (*MsgForwardFeesResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ForwardFees(ctx context.Context, req *MsgForwardFees) (*MsgForwardFeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardFees not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ForwardFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgForwardFees)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ForwardFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celestia.feeaddress.v1.Msg/ForwardFees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ForwardFees(ctx, req.(*MsgForwardFees))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "celestia.feeaddress.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardFees",
			Handler:    _Msg_ForwardFees_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "celestia/feeaddress/v1/tx.proto",
}

func (m *MsgForwardFees) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgForwardFees) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgForwardFees) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgForwardFeesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgForwardFeesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgForwardFeesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgForwardFees) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgForwardFeesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgForwardFees) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgForwardFees: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgForwardFees: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgForwardFeesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgForwardFeesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgForwardFeesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
