name: Buf Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: bufbuild/buf-setup-action@v1.50.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push tagged Protobuf schema release
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: buf push proto --label "${GITHUB_REF_NAME}"
