name: ci-release

# Run this workflow on push events (i.e. PR merge) to main or release branches,
# push events for new semantic version tags, and all PRs.
on:
  push:
    branches:
      - main
      - "v*"
    tags:
      - "v*"
  release:
    types: [published]
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  markdown-linter:
    uses: ./.github/workflows/markdown-linter.yml

  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  goreleaser:
    if: github.event_name == 'release'
    uses: ./.github/workflows/goreleaser.yml
    permissions: write-all
    secrets:
      RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
