name: github-pages

on:
  push:
    branches:
      - main
    paths:
      - specs/**
  pull_request:
  merge_group:
    paths:
      - specs/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 #v6.0.0

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@ee69d230fe19748b7abf22df32acaa93833fad08 #v2.0.0
        with:
          mdbook-version: "0.4.21"

      - name: Build book
        run: mdbook build specs

      - name: Deploy main
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e #v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./specs/book
          # keep_files is to prevent PR preview files from being overwritten.
          # If we need to overwrite such files, trigger this workflow manually.
          keep_files: ${{ github.event_name != 'workflow_dispatch' }}

      - name: Deploy PR preview
        # Only run this job if the PR was created from a branch on celestiaorg/celestia-app
        # because this job will fail for branches from forks.
        # https://github.com/celestiaorg/celestia-app/issues/1506
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9 #v1.8.1
        with:
          source-dir: ./specs/book
