name: goreleaser
on:
  workflow_call:
    secrets:
      RELEASE_APP_ID:
        required: true
      RELEASE_APP_PRIVATE_KEY:
        required: true

jobs:
  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Mint GitHub App installation token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 #v3.2.0
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: Create .release-env file
        run: |-
          echo 'GITHUB_TOKEN=${{ steps.app-token.outputs.token }}' >> .release-env
      - name: Check the .goreleaser.yaml config file
        run: make goreleaser-check

  goreleaser:
    needs: goreleaser-check
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && contains(github.ref, 'refs/tags/'))
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Ephemeral Go caches
        run: |
          echo "GOMODCACHE=$(mktemp -d)" >> $GITHUB_ENV
          echo "GOCACHE=$(mktemp -d)" >> $GITHUB_ENV
          echo "GOTMPDIR=$(mktemp -d)" >> $GITHUB_ENV
      - name: Mint GitHub App installation token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 #v3.2.0
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: Create .release-env file
        run: |-
          echo 'GITHUB_TOKEN=${{ steps.app-token.outputs.token }}' >> .release-env
      - name: Create prebuilt binaries and attach them to the GitHub release
        run: make prebuilt-binary
