name: project-automation
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add new issues to the core/app project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e #v1.0.2
        with:
          project-url: https://github.com/orgs/celestiaorg/projects/24
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
