name: project-automation
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add new issues to the core/app project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd #v2.0.0
        with:
          project-url: https://github.com/orgs/celestiaorg/projects/24
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
