name: Buf Push

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths:
      - "proto/**"

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: bufbuild/buf-action@v1
        with:
          # Include a GitHub token to ensure API requests aren't rate limited.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The Buf CLI input (i.e. the protobuf module sources)
          input: "proto"
          push: true
          token: ${{ secrets.BUF_TOKEN }}
